# Имя, которое отразится на платформе CTFd
name: "Peter blog"
# Ваш Telegram никнейм (не отображается на платформе)
author: "@kotz1k"
# Категория - название папки, в которой лежит таск
category: "web"
# Категория будет отображаться на платформе в описании таска. Поддерживается md формат 
description: |
  И решил царь наш великий открыть свою газету, а не пользоваться заморскими чудами
  И открыл он свою газету, а назвал ее "Peter blog".
  Да вот не задача, допустил ошибку в форме авторизации...
  Долго думал царь, что с этим делать. И решил, что проверит знания своего народа.
  Собрал всех на площади и молвил: "кто мне принесет информацию, доступную только админам, того щедро награжу"
# Ссылка на ваш ТГ аккаунт, чтобы с вами могли оперативно связаться по задаче
attribution: "Автор [@kotz1k](https://t.me/kotz1k)"
value: 1000
type: dynamic

# Reference - https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
extra:
    initial: 1000
    decay: 10
    minimum: 100

# Описание как коннектиться к вашей задаче. Сюда же можно и ссылку дать, если не в описании
connection_info: "ip:3000"

# Раскомментируйте, если хотите сделать так, чтобы у таска было ограниченное число попыток сдачи
# Мы в рамках VrnCTF не используем
# attempts: 5

# Все способы описать флаг
# flags:
#     # A static case sensitive flag
#     - flag{3xampl3}
#     # A static case sensitive flag created with a dictionary
#     - {
#         type: "static",
#         content: "flag{wat}",
#     }
#     # A static case insensitive flag
#     - {
#         type: "static",
#         content: "flag{wat}",
#         data: "case_insensitive",
#     }
#     # A regex case insensitive flag
#     - {
#         type: "regex",
#         content: "(.*)STUFF(.*)",
#         data: "case_insensitive",
#     }

flags:
  - vrnctf{n0_sql_inj3cti0n_f0r_tsar}

# Особо ни на что не влияет, по желанию можно раскомментировать и заполнить
# topics:
#     - sql injection

# Файлы из папки public, которые раздаем пользователям. Либо текстовые файлики, либо архивы
# Сильно жирные файлы раздаем через гугл-облако/яндекс-диск/линк с s3

# Хинты по умолчанию скрыты, сделайте их заранее, их откроем на половине соревнований на нерешенные таски
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free


# Если ваш таск зависит от другого таска, например, они идут друг за другом и без сдачи одного не будет доступен другой
# requirements:
#     - "Warmup"
#     - "Are you alive"

# visible/hidden на платформе
state: visible

# Не трогаем, версия спецификации
version: "0.1"

