apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
  labels:
    app: health-check-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check-service
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      serviceAccountName: health-check-sa
      containers:
      - name: health-check-service
        image: health-check-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: DEBUG
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: health-check-service
spec:
  selector:
    app: health-check-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-check-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: health-check-service
            port:
              number: 80
