apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-check-sa
  namespace: default
---
# Limited role for default service account (troubleshooting/maintenance like in real life)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maintenance-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-maintenance
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: maintenance-role
  apiGroup: rbac.authorization.k8s.io
---
# Admin privileges for health-check-sa (I lied above, that's how it works in real life: we just give everything admin just in case frfr)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: health-check-admin
subjects:
- kind: ServiceAccount
  name: health-check-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
