name: peter_blog

services:
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb_data:/data/db

volumes:
  mongodb_data: 