# Имя, которое отразится на платформе CTFd
name: "house"
# Ваш Telegram никнейм (не отображается на платформе)
author: "@jim_amlt"
# Категория - название папки, в которой лежит таск
category: "osint"
# Категория будет отображаться на платформе в описании таска. Поддерживается md формат
description: |
  Говорят, в домике с этого рисунка гостил кто-то очень известный. Только никак не могу вспомнить кто и где этот дом...
  Но раньше дома строили на века, не то что сейчас. Бревна не жалели, всегда брали про запас.
  Вот взять например этот домик, сколько же было свай у него в основании?
  
  Формат флага - `vrnctf{число}`
  
  ***Внимание! У вас ограниченное число попыток на команду! После их исчерпания флаг сдать будет невозможно!***
  
  ![Фотография](https://sun9-78.userapi.com/impg/tubo8KddF8LdheOD_LAkwJiVs4quS2VhYagAEg/dhGiw4V5Hcw.jpg?size=423x491&quality=95&sign=5e161141cb1889505393e5f79787e5f3&type=album)
# Ссылка на ваш ТГ аккаунт, чтобы с вами могли оперативно связаться по задаче
attribution: "Автор [@jim_amlt](https://t.me/jim_amlt)"
value: 100
type: dynamic

# Reference - https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
extra:
    initial: 100
    decay: 10
    minimum: 10

# Описание как коннектиться к вашей задаче. Сюда же можно и ссылку дать, если не в описании
#connection_info: "nc example.com 5432"

# Раскомментируйте, если хотите сделать так, чтобы у таска было ограниченное число попыток сдачи
# Мы в рамках VrnCTF не используем
attempts: 3

# Все способы описать флаг
# flags:
#     # A static case sensitive flag
#     - flag{3xampl3}
#     # A static case sensitive flag created with a dictionary
#     - {
#         type: "static",
#         content: "flag{wat}",
#     }
#     # A static case insensitive flag
#     - {
#         type: "static",
#         content: "flag{wat}",
#         data: "case_insensitive",
#     }
#     # A regex case insensitive flag
#     - {
#         type: "regex",
#         content: "(.*)STUFF(.*)",
#         data: "case_insensitive",
#     }

flags:
  - vrnctf{64}

# Особо ни на что не влияет, по желанию можно раскомментировать и заполнить
# topics:
#     - sql injection

# Файлы из папки public, которые раздаем пользователям. Либо текстовые файлики, либо архивы
# Сильно жирные файлы раздаем через гугл-облако/яндекс-диск/линк с s3
files:
#  - public/house.png
#  - public/app.py

# Хинты по умолчанию скрыты, сделайте их заранее, их откроем на половине соревнований на нерешенные таски
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

hints:
#  - Это домик в Заандаме
#  - Возможно, ответ в какой-то книге  

# Если ваш таск зависит от другого таска, например, они идут друг за другом и без сдачи одного не будет доступен другой
# requirements:
#     - "Warmup"
#     - "Are you alive"

# visible/hidden на платформе
state: visible

# Не трогаем, версия спецификации
version: "0.1"
